---
type: l2leaf

l2leaf:
  defaults:
    platform: cEOS-lab
    router_id_pool: 10.255.1.0/24
    loopback_ipv6_pool: 2001:DB8:A1::/48
    vtep_loopback_ipv6_pool: 2001:DB8:A2::/48
    virtual_router_mac_address: 02:1c:73:00:00:99
    spanning_tree_priority: 4096
    spanning_tree_mode: mstp
#    mlag_peer_address_family: ipv6
    mlag_peer_ipv6_pool: 2001:DB8:3::/48
    mlag_peer_l3_ipv6_pool: 2001:DB8:4::/48
    loopback_ipv4_pool: 10.255.1.0/24
    vtep_loopback_ipv4_pool: 10.255.2.0/27
    uplink_ipv4_pool: 10.255.203.0/26
    mlag_peer_ipv4_pool: 10.255.255.64/27
    mlag_peer_l3_ipv4_pool: 10.255.255.96/27



  node_groups:
    - group: TOWER-LEAF3
      nodes:
        - name: tower-leaf3-1
          id: 7
          mgmt_ip: 172.22.0.107/24
          uplink_switch_interfaces: [Ethernet8]
          uplink_switches: ['acc-leaf2-1']
          uplink_ipv6_pool: 2001:DB8:B31::/48
          bgp_as: 65107
        - name: tower-leaf3-2
          id: 8
          mgmt_ip: 172.22.0.108/24
          uplink_ipv6_pool: 2001:DB8:B32::/48
          bgp_as: 65108

# type: l2leaf

# l2leaf:
#   defaults:
#     platform: vEOS-lab
#     spanning_tree_mode: mstp

#   node_groups:
#     - group: DC1_L2_LEAF1
#       uplink_switches: [dc1-leaf1a, dc1-leaf1b]
#       nodes:
#         - name: dc1-leaf1c
#           id: 1
#           mgmt_ip: 172.16.1.151/24
#           uplink_switch_interfaces: [Ethernet8, Ethernet8]