#!/bin/bash
cd "$(dirname "$(readlink -f "$0")")"
rm -rf clab-interview-lab
clab destroy
set -x
jinja2 dualhomed.j2 sdf-server1.yaml > startscripts/sdf-server1.sh
jinja2 dualhomed.j2 sdf-server2.yaml > startscripts/sdf-server2.sh
jinja2 dualhomed.j2 center-position1.yaml > startscripts/center-position1.sh
jinja2 dualhomed.j2 tower-position1.yaml > startscripts/tower-position1.sh
jinja2 dualhomed.j2 rec-server.yaml > startscripts/rec-server.sh
jinja2 dualhomed.j2 radar.yaml > startscripts/radar.sh
jinja2 default.j2 tower-cam1.yaml > startscripts/tower-cam1.sh
jinja2 default.j2 tower-df1.yaml > startscripts/tower-df1.sh
jinja2 default.j2 radar-cam1.yaml > startscripts/radar-cam1.sh
set +x
clab deploy
