---
tenants:
  - name: ATC-FIDJI
    mac_vrf_vni_base: 10000
    vrfs:
      - name: VRF-RDR
        vrf_vni: 11
        svis:
          - id: 250
            name: VRFRDR_VLAN250_RDR
            enabled: true
            ip_address_virtual: 192.168.250.1/24
            ipv6_address_virtuals: [2001:DB8:D250::1/48]
      - name: VRF-CAM
        vrf_vni: 12
        svis:
          - id: 220
            name: VRFRDR_VLAN220_CAM_TOWER
            enabled: true
            ip_address_virtual: 192.168.220.1/24
            ipv6_address_virtuals: [2001:DB8:D220::1/48]
          - id: 221
            name: VRFRDR_VLAN250_CAM_RDR
            enabled: true
            ip_address_virtual: 192.168.221.1/24
            ipv6_address_virtuals: [2001:DB8:D221::1/48]


