---
type: spine

spine:
  defaults:
    platform: cEOS-lab
    router_id_pool: 10.255.0.0/24
    loopback_ipv6_pool: 2001:DB8:A1::/48
    loopback_ipv4_pool: 10.255.1.0/24



  nodes:
    - name: rz-spine1
      id: 1
      mgmt_ip: 172.22.0.101/24
      bgp_as: 65101

    - name: rz-spine2
      id: 2
      mgmt_ip: 172.22.0.102/24
      bgp_as: 65102
