---
port_profiles:

  - profile: SDF
    mode: trunk
    vlans: "12,250,3401,3402"
    native_vlan: "12"
    spanning_tree_portfast: edge

  - profile: CLIENT
    mode: trunk
    vlans: "11,3401,3402"
    native_vlan: "11"
    spanning_tree_portfast: edge


servers:
  - name: sdf-server1
    adapters:
      - endpoint_ports: [ eth1, eth2 ]
        switch_ports: [ Ethernet5, Ethernet5 ]
        switches: [ rz-sdf-leaf1-1, rz-sdf-leaf1-2 ]
        profile: SDF
        port_channel:
          endpoint_port_channel: Bond0
          mode: active
        ethernet_segment:
          short_esi: 0001:0001:0001
  - name: sdf-server2
    adapters:
      - endpoint_ports: [ eth1, eth2 ]
        switch_ports: [ Ethernet6, Ethernet6 ]
        switches: [ rz-sdf-leaf1-1, rz-sdf-leaf1-2 ]
        profile: SDF
        port_channel:
          endpoint_port_channel: Bond0
          mode: active
        ethernet_segment:
          short_esi: 0001:0001:0002
  - name: rec-server
    adapters:
      - endpoint_ports: [ eth1, eth2 ]
        switch_ports: [ Ethernet7, Ethernet7 ]
        switches: [ rz-sdf-leaf1-1, rz-sdf-leaf1-2 ]
        mode: trunk
        vlans: "12,219"
        native_vlan: "12"
        spanning_tree_portfast: edge
        port_channel:
          endpoint_port_channel: Bond0
          mode: active
        ethernet_segment:
          short_esi: 0001:0001:0003
  - name: center-position1
    adapters:
      - endpoint_ports: [ eth1, eth2 ]
        switch_ports: [ Ethernet3, Ethernet3 ]
        switches: [ center-leaf2-1, center-leaf2-2 ]
        profile: CLIENT
        port_channel:
          endpoint_port_channel: Bond0
          mode: active
        ethernet_segment:
          short_esi: 0001:0002:0001
  - name: tower-position1
    adapters:
      - endpoint_ports: [ eth1, eth2 ]
        switch_ports: [ Ethernet5, Ethernet5 ]
        switches: [ tower-leaf3-1, tower-leaf3-2]
        profile: CLIENT
        port_channel:
          endpoint_port_channel: Bond0
          mode: active
        ethernet_segment:
          short_esi: 0001:0003:0001
  - name: tower-cam1
    adapters:
      - endpoint_ports: [ eth1 ]
        switch_ports: [ Ethernet6 ]
        switches: [ tower-leaf3-2 ]
        vlans: 220
        mode: access
        spanning_tree_portfast: edge
  - name: tower-df1
    adapters:
      - endpoint_ports: [ eth1 ]
        switch_ports: [ Ethernet6 ]
        switches: [ tower-leaf3-1 ]
        vlans: 250
        mode: access
        spanning_tree_portfast: edge
  - name: radar-cam1
    adapters:
      - endpoint_ports: [ eth1 ]
        switch_ports: [ Ethernet5 ]
        switches: [ radarstation-edge1-1 ]
        vlans: 221
        mode: access
        spanning_tree_portfast: edge
  - name: radar
    adapters:
      - endpoint_ports: [ eth1, eth2 ]
        switch_ports: [ Ethernet6, Ethernet6 ]
        switches: [ radarstation-edge1-1, radarstation-edge1-2]
        mode: access
        vlans: 250
        port_channel:
          endpoint_port_channel: Bond0
          mode: active
        ethernet_segment:
          short_esi: 0002:0001:0001

  # - name: dc1-leaf2-server1
  #   adapters:
  #     - endpoint_ports: [PCI1, PCI2]
  #       switch_ports: [Ethernet5, Ethernet5]
  #       switches: [dc1-leaf2a, dc1-leaf2b]
  #       vlans: 11-12,21-22
  #       native_vlan: 4092
  #       mode: trunk
  #       spanning_tree_portfast: edge
  #       port_channel:
  #         mode: active

  #     - endpoint_ports: [iLO]
  #       switch_ports: [Ethernet5]
  #       switches: [dc1-leaf2c]
  #       vlans: 11
  #       mode: access
  #       spanning_tree_portfast: edge
