#!/usr/bin/env python3
from ansible.parsing.dataloader import DataLoader
from ansible.inventory.manager import InventoryManager
from graphviz import Digraph
from flask import Flask, Response, render_template_string
import threading
import requests
import json
import urllib3
import base64

app = Flask(__name__)

# Globals
inventory_path = "inventory.yml"
group_name = "FABRIC"
username = "admin"
password = "admin"
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)


def execute_command(hostname: str, cmd: str) -> dict:
    url = f"https://{hostname}/command-api"
    payload = {
        "jsonrpc": "2.0",
        "method": "runCmds",
        "params": {
            "version": 1,
            "cmds": [{"cmd": "enable", "input": password}, cmd],
            "format": "json",
        },
        "id": 1,
    }
    response = requests.post(
        url,
        data=json.dumps(payload),
        auth=(username, password),
        verify=False,  # only disable if you use self‑signed certs
    )
    result = response.json()
    result["hostname"] = hostname
    return result

def get_hosts():
    inventory = InventoryManager(DataLoader(), sources=[inventory_path])
    group = inventory.groups.get(group_name)
    if group:
        hosts = [h.name for h in group.get_hosts()]
    else:
        pass
    return hosts


def get_information(h):
    result = {}
    result["BGP"] = execute_command(h, "show bgp summary")
    result["BGP_PEERS"] = execute_command(h, "show bgp neighbors")
    result["MAC"] = execute_command(h, "show mac address-table count")
    result["HOSTNAME"] = h
    return result


def count_macs(data):
    vlan_counts = data["result"][1]["vlanCounts"]

    total_dynamic = 0
    total_unicast = 0
    total_multicast = 0

    for vlan, counts in vlan_counts.items():
        total_dynamic += counts.get("dynamic", 0)
        total_unicast += counts.get("unicast", 0)
        total_multicast += counts.get("multicast", 0)

    return f"D: {total_dynamic} U{total_unicast}"


@app.route("/")
def index():
    png1 = base64.b64encode(render("ipv4Unicast", False)).decode("utf-8")
    png2 = base64.b64encode(render("l2VpnEvpn", False)).decode("utf-8")
    png3 = base64.b64encode(render("ipv4Unicast", True)).decode("utf-8")

    html = """
    <h2>ipv4Unicast</h2>
    <img src="data:image/png;base64,{{ img1 }}" />

    <hr>

    <h2>l2VpnEvpn</h2>
    <img src="data:image/png;base64,{{ img2 }}" />

    <hr>

    <h2>Rates</h2>
    <img src="data:image/png;base64,{{ img3 }}" />
    """

    return render_template_string(html, img1=png1, img2=png2, img3=png3)


def render(afi: str, printBps: bool):
    hosts = get_hosts()
    dot = Digraph("bgp_topology", format="png", engine="sfdp")
    dot.attr(rankdir="TB")
    dot.attr("node", shape="box", style="filled", fillcolor="lightgrey")
    dot.graph_attr.update({
    "sep": "+10",
    "dpi": "80"
    })
    if afi == "ipv4Unicast":
        dot.node("GRE-ROUTER", label=f"GRE-ROUTER")
    for h in hosts:
        try:
            info = get_information(h)
        except:
            continue
        bgp_information = info["BGP"]
        bgp_peer_information = info["BGP_PEERS"]
        mac_information = info["MAC"]
        hostname = info["HOSTNAME"]
        try:
            router = bgp_information["result"][1]["vrfs"]["default"]
            peers = bgp_peer_information["result"][1]["vrfs"]["default"]["peerList"]
        except:
            continue
        try:
            mac_count = count_macs(mac_information)
        except:
            mac_count = 0
        router_id = router["routerId"]
        dot.node(router_id, label=f"{hostname}\nASN {router['asn']}\n MAC {mac_count}")
        for peer in peers:
            try:
                configured_afis = peer["neighborCapabilities"]["multiprotocolCaps"]
            except:
                configured_afis = {}
            if afi not in configured_afis:
                continue
            elif afi in peer["afiSafiInfo"]:
                peer_interface = peer["ifName"]
                rates = execute_command(hostname, f"show interfaces {peer_interface} counters rates")
                try:
                    rateOut = rates["result"][1]["interfaces"][peer_interface]["outBpsRate"]
                    rateOut = rateOut / 1000
                    rateOut = round(rateOut, 0)
                except:
                    rateOut = "-"
            state = peer["state"]
            peer_router_id = peer["routerId"]
            if "10.255.1.25" in peer_router_id:
                peer_router_id = "GRE-ROUTER"
            color = "green" if state == "Established" else "red"
            if printBps:
                try:
                    match float(rateOut):
                        case x if x < 1:
                            color = "blue"
                        case x if x < 10:
                            color = "green"
                        case x if x < 2000:
                            color = "orange"
                        case x if x > 2000:
                            color = "red"
                except:
                    color = "grey"
                dot.edge(router_id, peer_router_id, label=f"{rateOut} kB/s", color=color)
            else:
                dot.edge(router_id, peer_router_id, label=f"{state}", color=color)

    png = dot.pipe(format="png")
    return png 

def run():
    app.run(host="0.0.0.0", port=8080)


if __name__ == "__main__":
    run()


