---
type: l3leaf

l3leaf:
  defaults:
    platform: cEOS-lab
    router_id_pool: 10.255.1.0/24
    loopback_ipv6_pool: 2001:DB8:A1::/48
    vtep_loopback_ipv6_pool: 2001:DB8:A2::/48
    uplink_switches: ['rz-spine1', 'rz-spine2']
    uplink_ipv6_pool: 2001:DB8:B2::/48
    virtual_router_mac_address: 02:1c:73:00:00:99
    spanning_tree_priority: 4096
    spanning_tree_mode: mstp
    mlag: false
    loopback_ipv4_pool: 10.255.1.0/24
    vtep_loopback_ipv4_pool: 10.255.2.0/27
    uplink_ipv4_pool: 10.255.202.0/26

  node_groups:
    - group: CENTER-LEAF2
      nodes:
        - name: center-leaf2-1
          id: 5
          mgmt_ip: 172.22.0.105/24
          uplink_switch_interfaces: [Ethernet3, Ethernet3]
          bgp_as: 65105
        - name: center-leaf2-2
          id: 6
          mgmt_ip: 172.22.0.106/24
          uplink_switch_interfaces: [Ethernet4, Ethernet4]
          bgp_as: 65106