! Command: show running-config
! device: tower-leaf3-2 (cEOSLab, EOS-4.35.0F-44178984.4350F (engineering build))
!
no aaa root
!
username admin privilege 15 role network-admin secret sha512 $6$KOB7dXerN/zU0qwP$AyKdyby06XyR3P0PQuHFXZNJrBRefN4UZU/C0xxp7eaYcsMIqII8knTPSQe3abzVzjwSpvtUL55AnE.i/pc/s/
!
management api http-commands
   no shutdown
   !
   vrf MGMT
      no shutdown
!
vlan internal order ascending range 1006 1199
!
no service interface inactive port-id allocation disabled
!
transceiver qsfp default-mode 4x10G
!
service routing protocols model multi-agent
!
hostname tower-leaf3-2
!
spanning-tree mode mstp
no spanning-tree vlan-id 4094
spanning-tree mst 0 priority 4096
!
system l1
   unsupported speed action error
   unsupported error-correction action error
!
vlan 11
   name VRFEXT_VLAN11_CLIENT
!
vlan 12
   name VRF10_VLAN12_SERVER
!
vlan 219
   name VRFRDR_VLAN219_REC
!
vlan 220
   name VRFRDR_VLAN220_CAM_TOWER
!
vlan 250
   name VRFRDR_VLAN250_RDR
!
vlan 3401
   name CHANNEL-A
!
vlan 3402
   name CHANNEL-B
!
vlan 4094
   name MLAG
   trunk group MLAG
!
vrf instance MGMT
!
interface Port-Channel3
   description MLAG_tower-leaf3-1_Port-Channel3
   switchport mode trunk
   switchport trunk group MLAG
!
interface Port-Channel5
   description SERVER_tower-position1_Bond0
   switchport trunk native vlan 11
   switchport trunk allowed vlan 11,3401-3402
   switchport mode trunk
   mlag 5
   spanning-tree portfast edge
!
interface Ethernet3
   description MLAG_tower-leaf3-1_Ethernet3
   channel-group 3 mode active
!
interface Ethernet4
   description MLAG_tower-leaf3-1_Ethernet4
   channel-group 3 mode active
!
interface Ethernet5
   description SERVER_tower-position1_eth2
   channel-group 5 mode active
!
interface Ethernet6
   description SERVER_tower-cam1_eth1
   switchport access vlan 220
   spanning-tree portfast edge
!
interface Management0
   description OOB_MANAGEMENT
   vrf MGMT
   ip address 172.22.0.108/24
!
interface Vlan4094
   description MLAG
   mtu 1500
   no autostate
   ip address 10.255.255.77/31
!
no ip routing
no ip routing vrf MGMT
!
mlag configuration
   domain-id TOWER-LEAF3
   local-interface Vlan4094
   peer-address 10.255.255.76
   peer-link Port-Channel3
   reload-delay mlag 300
   reload-delay non-mlag 330
!
ip route vrf MGMT 0.0.0.0/0 172.22.0.1
!
router multicast
   ipv4
      software-forwarding kernel
   !
   ipv6
      software-forwarding kernel
!
end